-- Baseline generated by drizzle-kit from packages/tool-telemetry/src/schema.ts.
-- IF NOT EXISTS was added by hand: production and preview already have these
-- tables from the retired 0001_tool_telemetry.sql, so applying this is a no-op there.
CREATE TABLE IF NOT EXISTS `tool_runs` (
	`id` text PRIMARY KEY NOT NULL,
	`tool_id` text NOT NULL,
	`status` text NOT NULL,
	`started_at` text NOT NULL,
	`duration_ms` integer,
	`input_bytes` integer,
	`output_bytes` integer,
	`error_code` text,
	`metadata` text,
	CONSTRAINT "tool_runs_status_check" CHECK("tool_runs"."status" IN ('started', 'succeeded', 'failed')),
	CONSTRAINT "tool_runs_metadata_check" CHECK("tool_runs"."metadata" IS NULL OR json_valid("tool_runs"."metadata"))
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `idx_tool_runs_tool_id_started_at` ON `tool_runs` (`tool_id`,`started_at`);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `idx_tool_runs_status_started_at` ON `tool_runs` (`status`,`started_at`);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `tool_status` (
	`tool_id` text PRIMARY KEY NOT NULL,
	`status` text NOT NULL,
	`last_run_at` text,
	`failure_rate_24h` real,
	`median_duration_ms` integer,
	`median_reduction_pct` real,
	`updated_at` text NOT NULL
);
