import {
  FileImage,
  FileJson,
  Image,
  Mic,
  Music,
  Table,
  Type,
  Video,
  type LucideIcon,
} from 'lucide-react';

const iconByToolId: Readonly<Record<string, LucideIcon>> = {
  'heic-to-jpg': Image,
  'heic-to-jpeg': Image,
  'heic-to-png': Image,
  'heic-to-pdf': FileImage,
  'heif-to-jpg': Image,
  'heif-to-png': Image,
  'heif-to-pdf': FileImage,
  'pdf-to-jpg': FileImage,
  'pdf-to-png': FileImage,
  'pdf-editor': FileImage,
  'pdf-editor-extension': FileImage,
  'pdf-editor-mac': FileImage,
  'pdf-editor-windows': FileImage,
  'pdf-reader': FileImage,
  'pdf-reader-extension': FileImage,
  'pdf-reader-mac': FileImage,
  'pdf-reader-windows': FileImage,
  'pdf-viewer': FileImage,
  'pdf-viewer-extension': FileImage,
  'pdf-viewer-windows': FileImage,
  'jpg-to-pdf': FileImage,
  'jpeg-to-pdf': FileImage,
  'jpg-to-png': Image,
  'png-to-jpg': Image,
  'jpeg-to-png': Image,
  'jpeg-to-jpg': Image,
  'webp-to-png': Image,
  'png-to-webp': Image,
  'jpg-to-webp': Image,
  'jpeg-to-webp': Image,
  'gif-to-webp': Image,
  'webp-to-jpg': Image,
  'webp-to-jpeg': Image,
  'avif-to-png': Image,
  'avif-to-jpg': Image,
  'avif-to-jpeg': Image,
  'bmp-to-jpg': Image,
  'bmp-to-png': Image,
  'ico-to-png': Image,
  'gif-to-jpg': Image,
  'gif-to-png': Image,
  'jfif-to-jpg': Image,
  'jfif-to-jpeg': Image,
  'jfif-to-png': Image,
  'jfif-to-pdf': FileImage,
  'cr2-to-jpg': Image,
  'cr3-to-jpg': Image,
  'dng-to-jpg': Image,
  'arw-to-jpg': Image,
  'jpg-to-svg': FileImage,
  'png-optimizer': Image,
  'csv-combiner': Table,
  'json-to-csv': FileJson,
  'character-counter': Type,
  'mkv-to-mp4': Video,
  'mkv-to-webm': Video,
  'mkv-to-avi': Video,
  'mkv-to-mov': Video,
  'mkv-to-gif': Image,
  'mkv-to-mp3': Music,
  'mkv-to-wav': Music,
  'mkv-to-ogg': Music,
  'batch-compress-png': Image,
  'audio-to-text': Mic,
  'audio-to-transcript': Mic,
  'mp3-to-transcript': Mic,
  'mp4-to-transcript': Mic,
  'video-to-transcript': Mic,
  'tiktok-to-transcript': Mic,
  'youtube-to-transcript': Mic,
  'youtube-to-transcript-generator': Mic,
  'video-downloader': Video,
  'download-loom-videos': Video,
  'video-editor': Video,
  'image-editor': Image,
  'audio-editor': Music,
};

export function getToolIcon(toolId: string): LucideIcon {
  if (toolId.startsWith('download-') || toolId.endsWith('-downloader')) {
    return Video;
  }
  return iconByToolId[toolId] ?? Image;
}
