// Worker entry: the OpenNext worker wrapped with Sentry (issue #162).
// Reporting is off unless the SENTRY_DSN var is set for the environment.
import { withSentry } from "@sentry/cloudflare";

// Both are generated by `pnpm cf:build` (opennextjs-cloudflare build and
// scripts/build-cloudflare.mjs).
import nextApp from "./.open-next/worker.js";
import release from "./.open-next/release.mjs";
import { SENTRY_DEFAULTS, scrubEvent, sentryRelease } from "./lib/sentry-scrub.ts";

export default withSentry(
  (env) => ({
    ...SENTRY_DEFAULTS,
    dsn: env.SENTRY_DSN,
    enabled: Boolean(env.SENTRY_DSN),
    environment: env.NEXT_PUBLIC_SITE_ENV || "local",
    release: sentryRelease(release),
    beforeSend: (event) => scrubEvent(event),
  }),
  nextApp,
);

// OpenNext's Durable Object and queue classes.
export * from "./.open-next/worker.js";
